name: debt_manager
description: A new Flutter project for managing debts.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # لإضافة الدعم للغة العربية
    sdk: flutter

  # للواجهة والأيقونات
  cupertino_icons: ^1.0.2

  # لإدارة الحالة (State Management)
  provider: ^6.0.5

  # لتخزين الملفات محلياً
  path_provider: ^2.0.12

  # لتهيئة التواريخ
  intl: ^0.20.2
  
  # لتوليد معرفات فريدة
  uuid: ^4.4.0

  # لتصدير الملفات
  pdf: ^3.10.1         # لإنشاء ملفات PDF
  printing: ^5.10.4    # لمشاركة وطباعة PDF
  csv: ^5.0.2          # لإنشاء ملفات CSV (Excel)
  share_plus: ^6.3.4   # لمشاركة الملفات

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # لإضافة خطوط مخصصة
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
