name: Build Flutter Android

on:
  push:
    branches:
      - main # يتغير هذا حسب اسم الفرع الرئيسي لديك

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0' # يمكنك تغيير هذا الإصدار ليتناسب مع إصدار مشروعك
        channel: 'stable'

    - name: Get Flutter dependencies
      run: flutter pub get
      working-directory: ./my_apmanager

    - name: Build APK
      run: flutter build apk --release
      working-directory: ./my_apmanager

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: my_apmanager/build/app/outputs/flutter-apk/app-release.apk
